In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
bc = pd.read_csv('F:\Kaggle\cs-test.csv')

In [3]:
bc.head(30)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,NaN,0.885519,43,0,0.177513,5700.0,4,0,0,0,0.0
1,2,NaN,0.463295,57,0,0.527237,9141.0,15,0,4,0,2.0
2,3,NaN,0.043275,59,0,0.687648,5083.0,12,0,1,0,2.0
3,4,NaN,0.280308,38,1,0.925961,3200.0,7,0,2,0,0.0
4,5,NaN,1.000000,27,0,0.019917,3865.0,4,0,0,0,1.0
5,6,NaN,0.509791,63,0,0.342429,4140.0,4,0,0,0,1.0
6,7,NaN,0.587778,50,0,1048.000000,0.0,5,0,0,0,3.0
7,8,NaN,0.046149,79,1,0.369170,3301.0,8,0,1,0,1.0
8,9,NaN,0.013527,68,0,2024.000000,NaN,4,0,1,0,0.0
9,10,NaN,1.000000,23,98,0.000000,0.0,0,98,0,98,0.0
10,11,NaN,0.028485,37,0,0.319687,7400.0,8,0,1,0,1.0
11,12,NaN,0.085077,52,0,0.903552,4250.0,6,0,2,0,0.0
12,13,NaN,0.010596,68,0,0.007782,3854.0,16,0,0,0,0.0
13,14,NaN,0.380679,30,0,0.377449,2500.0,12,0,0,0,1.0
14,15,NaN,0.556894,56,0,0.697347,6822.0,14,0,1,0,1.0
15,16,NaN,0.079056,28,0,0.105831,7133.0,8,0,0,0,0.0
16,17,NaN,0.543013,72,0,0.461786,5900.0,10,0,2,0,1.0
17,18,NaN,0.112346,37,0,0.144326,2916.0,7,0,0,0,0.0
18,19,NaN,0.648285,29,0,0.174850,4500.0,4,0,0,1,1.0
19,20,NaN,0.686406,43,0,487.000000,NaN,10,0,0,0,1.0
20,21,NaN,0.085910,48,0,0.196156,8844.0,8,0,1,0,1.0
21,22,NaN,0.158549,61,0,0.353158,11920.0,13,0,1,0,0.0
22,23,NaN,0.009303,69,0,0.384451,6083.0,4,0,2,0,0.0
23,24,NaN,0.957442,69,2,0.666338,3041.0,8,1,1,1,1.0
24,25,NaN,0.442489,50,1,0.286555,8500.0,17,0,1,0,2.0
25,26,NaN,0.125267,51,0,3825.000000,NaN,10,0,2,0,0.0
26,27,NaN,1.000000,45,0,0.000000,4750.0,1,0,0,0,1.0
27,28,NaN,0.181481,67,0,1509.000000,NaN,12,0,1,0,0.0
28,29,NaN,0.729397,34,0,0.335555,7500.0,6,0,2,0,1.0
29,30,NaN,0.024445,47,0,5810.000000,NaN,20,0,2,0,2.0

In [4]:
bc.dtypes

Unnamed: 0                                int64
SeriousDlqin2yrs                        float64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
dtype: object

In [5]:
bc['SeriousDlqin2yrs']=bc['SeriousDlqin2yrs'].fillna(0)

In [6]:
bc['RevolvingUtilizationOfUnsecuredLines'].head(51)

0     0.885519
1     0.463295
2     0.043275
3     0.280308
4     1.000000
5     0.509791
6     0.587778
7     0.046149
8     0.013527
9     1.000000
10    0.028485
11    0.085077
12    0.010596
13    0.380679
14    0.556894
15    0.079056
16    0.543013
17    0.112346
18    0.648285
19    0.686406
20    0.085910
21    0.158549
22    0.009303
23    0.957442
24    0.442489
25    0.125267
26    1.000000
27    0.181481
28    0.729397
29    0.024445
30    0.691411
31    0.000000
32    0.000000
33    0.817480
34    1.008267
35    0.423358
36    0.282515
37    0.142127
38    0.022738
39    0.005893
40    0.603510
41    0.715499
42    0.640014
43    0.025266
44    0.190885
45    0.003449
46    0.013049
47    0.222961
48    0.019542
49    0.524461
50    0.083717
Name: RevolvingUtilizationOfUnsecuredLines, dtype: float64

In [7]:
bc.isnull().sum()

Unnamed: 0                                  0
SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           20103
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       2626
dtype: int64

In [8]:
bc['MonthlyIncome']=bc['MonthlyIncome'].fillna(0)

In [154]:
bc.head(15)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado,Nulos_NumberOfDependents,Limite_DebtRatio
0,1,0,0.885519,43,0,0.177513,5700.0,4,0.0,0,0,0.0,0,0,0,0
1,2,0,0.463295,57,0,0.527237,9141.0,15,0.0,4,0,2.0,0,0,0,0
2,3,0,0.043275,59,0,0.687648,5083.0,12,0.0,1,0,2.0,0,0,0,0
3,4,0,0.280308,38,1,0.925961,3200.0,7,0.0,2,0,0.0,0,0,0,0
4,5,0,1.000000,27,0,0.019917,3865.0,4,0.0,0,0,1.0,0,0,0,0
5,6,0,0.509791,63,0,0.342429,4140.0,4,0.0,0,0,1.0,0,0,0,0
6,7,0,0.587778,50,0,0.274230,5450.0,5,0.0,0,0,3.0,1,0,0,1
7,8,0,0.046149,79,1,0.369170,3301.0,8,0.0,1,0,1.0,0,0,0,0
8,9,0,0.013527,68,0,0.274230,5450.0,4,0.0,1,0,0.0,1,0,0,1
9,11,0,0.028485,37,0,0.319687,7400.0,8,0.0,1,0,1.0,0,0,0,0
10,12,0,0.085077,52,0,0.903552,4250.0,6,0.0,2,0,0.0,0,0,0,0
11,13,0,0.010596,68,0,0.007782,3854.0,16,0.0,0,0,0.0,0,0,0,0
12,14,0,0.380679,30,0,0.377449,2500.0,12,0.0,0,0,1.0,0,0,0,0
13,15,0,0.556894,56,0,0.697347,6822.0,14,0.0,1,0,1.0,0,0,0,0
14,16,0,0.079056,28,0,0.105831,7133.0,8,0.0,0,0,0.0,0,0,0,0

In [11]:
#Limite em DebtRation, valores muitos altos como Outliers.Podendo ser um erro de cadastro, em comum a renda fixa do usario com o limite que ele possa gastar.
#Exemplo: ele ganha R$5000 e tem um divida de Milhões, ou um erro de preenchimento no sistema onde o usuário não informou sua renda.
#Também criando uma coluna nova chamada 'Limite_DebtRatio' para todos os valores do limite_aceitavel(0.274230103) como  1.
limite = 1.0

In [12]:
limite_aceitavel=bc.loc[bc['DebtRatio'] <= limite, 'DebtRatio'].median()

In [13]:
limite_aceitavel

0.274230103

In [14]:
bc.loc[bc['DebtRatio'] > limite, 'DebtRatio'] = limite_aceitavel

In [142]:
bc['Limite_DebtRatio'] = (bc['DebtRatio'] == 0.274230103).astype(int)

In [15]:
bc.head(10)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.0,0.885519,43,0,0.177513,5700.0,4,0,0,0,0.0
1,2,0.0,0.463295,57,0,0.527237,9141.0,15,0,4,0,2.0
2,3,0.0,0.043275,59,0,0.687648,5083.0,12,0,1,0,2.0
3,4,0.0,0.280308,38,1,0.925961,3200.0,7,0,2,0,0.0
4,5,0.0,1.000000,27,0,0.019917,3865.0,4,0,0,0,1.0
5,6,0.0,0.509791,63,0,0.342429,4140.0,4,0,0,0,1.0
6,7,0.0,0.587778,50,0,0.274230,0.0,5,0,0,0,3.0
7,8,0.0,0.046149,79,1,0.369170,3301.0,8,0,1,0,1.0
8,9,0.0,0.013527,68,0,0.274230,0.0,4,0,1,0,0.0
9,10,0.0,1.000000,23,98,0.000000,0.0,0,98,0,98,0.0

In [155]:
bc[bc['SeriousDlqin2yrs'] ==0].head(15)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado,Nulos_NumberOfDependents,Limite_DebtRatio
0,1,0,0.885519,43,0,0.177513,5700.0,4,0.0,0,0,0.0,0,0,0,0
1,2,0,0.463295,57,0,0.527237,9141.0,15,0.0,4,0,2.0,0,0,0,0
2,3,0,0.043275,59,0,0.687648,5083.0,12,0.0,1,0,2.0,0,0,0,0
3,4,0,0.280308,38,1,0.925961,3200.0,7,0.0,2,0,0.0,0,0,0,0
4,5,0,1.000000,27,0,0.019917,3865.0,4,0.0,0,0,1.0,0,0,0,0
5,6,0,0.509791,63,0,0.342429,4140.0,4,0.0,0,0,1.0,0,0,0,0
6,7,0,0.587778,50,0,0.274230,5450.0,5,0.0,0,0,3.0,1,0,0,1
7,8,0,0.046149,79,1,0.369170,3301.0,8,0.0,1,0,1.0,0,0,0,0
8,9,0,0.013527,68,0,0.274230,5450.0,4,0.0,1,0,0.0,1,0,0,1
9,11,0,0.028485,37,0,0.319687,7400.0,8,0.0,1,0,1.0,0,0,0,0
10,12,0,0.085077,52,0,0.903552,4250.0,6,0.0,2,0,0.0,0,0,0,0
11,13,0,0.010596,68,0,0.007782,3854.0,16,0.0,0,0,0.0,0,0,0,0
12,14,0,0.380679,30,0,0.377449,2500.0,12,0.0,0,0,1.0,0,0,0,0
13,15,0,0.556894,56,0,0.697347,6822.0,14,0.0,1,0,1.0,0,0,0,0
14,16,0,0.079056,28,0,0.105831,7133.0,8,0.0,0,0,0.0,0,0,0,0

In [17]:
bc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101503 entries, 0 to 101502
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            101503 non-null  int64
 1   SeriousDlqin2yrs                      101503 non-null  float64
 2   RevolvingUtilizationOfUnsecuredLines  101503 non-null  float64
 3   age                                   101503 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  101503 non-null  int64
 5   DebtRatio                             101503 non-null  float64
 6   MonthlyIncome                         101503 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       101503 non-null  int64
 8   NumberOfTimes90DaysLate               101503 non-null  int64
 9   NumberRealEstateLoansOrLines          101503 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  101503 non-null  int64
 11  NumberOfDependents                    98877 non-null   float64
dtypes: float64(5), int64(7)
memory usage: 9.3 MB

In [156]:
bc.head(50)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado,Nulos_NumberOfDependents,Limite_DebtRatio
0,1,0,0.885519,43,0,0.177513,5700.0,4,0.0,0,0,0.0,0,0,0,0
1,2,0,0.463295,57,0,0.527237,9141.0,15,0.0,4,0,2.0,0,0,0,0
2,3,0,0.043275,59,0,0.687648,5083.0,12,0.0,1,0,2.0,0,0,0,0
3,4,0,0.280308,38,1,0.925961,3200.0,7,0.0,2,0,0.0,0,0,0,0
4,5,0,1.000000,27,0,0.019917,3865.0,4,0.0,0,0,1.0,0,0,0,0
5,6,0,0.509791,63,0,0.342429,4140.0,4,0.0,0,0,1.0,0,0,0,0
6,7,0,0.587778,50,0,0.274230,5450.0,5,0.0,0,0,3.0,1,0,0,1
7,8,0,0.046149,79,1,0.369170,3301.0,8,0.0,1,0,1.0,0,0,0,0
8,9,0,0.013527,68,0,0.274230,5450.0,4,0.0,1,0,0.0,1,0,0,1
9,11,0,0.028485,37,0,0.319687,7400.0,8,0.0,1,0,1.0,0,0,0,0
10,12,0,0.085077,52,0,0.903552,4250.0,6,0.0,2,0,0.0,0,0,0,0
11,13,0,0.010596,68,0,0.007782,3854.0,16,0.0,0,0,0.0,0,0,0,0
12,14,0,0.380679,30,0,0.377449,2500.0,12,0.0,0,0,1.0,0,0,0,0
13,15,0,0.556894,56,0,0.697347,6822.0,14,0.0,1,0,1.0,0,0,0,0
14,16,0,0.079056,28,0,0.105831,7133.0,8,0.0,0,0,0.0,0,0,0,0
15,17,0,0.543013,72,0,0.461786,5900.0,10,0.0,2,0,1.0,0,0,0,0
16,18,0,0.112346,37,0,0.144326,2916.0,7,0.0,0,0,0.0,0,0,0,0
17,19,0,0.648285,29,0,0.174850,4500.0,4,0.0,0,1,1.0,0,0,0,0
18,20,0,0.686406,43,0,0.274230,5450.0,10,0.0,0,0,1.0,1,0,0,1
19,21,0,0.085910,48,0,0.196156,8844.0,8,0.0,1,0,1.0,0,0,0,0
20,22,0,0.158549,61,0,0.353158,11920.0,13,0.0,1,0,0.0,0,0,0,0
21,23,0,0.009303,69,0,0.384451,6083.0,4,0.0,2,0,0.0,0,0,0,0
22,24,0,0.957442,69,2,0.666338,3041.0,8,1.0,1,1,1.0,0,0,0,0
23,25,0,0.442489,50,1,0.286555,8500.0,17,0.0,1,0,2.0,0,0,0,0
24,26,0,0.125267,51,0,0.274230,5450.0,10,0.0,2,0,0.0,1,0,0,1
25,27,0,1.000000,45,0,0.000000,4750.0,1,0.0,0,0,1.0,0,0,0,0
26,28,0,0.181481,67,0,0.274230,5450.0,12,0.0,1,0,0.0,1,0,0,1
27,29,0,0.729397,34,0,0.335555,7500.0,6,0.0,2,0,1.0,0,0,0,0
28,30,0,0.024445,47,0,0.274230,5450.0,20,0.0,2,0,2.0,1,0,0,1
29,31,0,0.691411,44,0,0.173777,4804.0,10,0.0,0,0,0.0,0,0,0,0
30,32,0,0.000000,55,0,0.274230,5450.0,5,0.0,1,0,0.0,1,0,0,1
31,33,0,0.000000,57,0,0.212447,4000.0,12,0.0,0,0,0.0,0,0,0,0
32,34,0,0.817480,54,0,0.132721,4354.0,6,0.0,0,0,0.0,0,0,0,0
33,35,0,0.143128,61,4,0.261173,8166.0,14,0.0,1,0,1.0,0,0,0,0
34,36,0,0.423358,49,0,0.616301,2600.0,13,0.0,1,0,1.0,0,0,0,0
35,37,0,0.282515,32,0,0.492901,5000.0,10,0.0,1,0,1.0,0,0,0,0
36,38,0,0.142127,56,0,0.274230,5450.0,9,0.0,2,0,2.0,1,0,0,1
37,39,0,0.022738,41,0,0.343161,5833.0,5,0.0,1,0,3.0,0,0,0,0
38,40,0,0.005893,57,1,0.386379,11819.0,25,0.0,4,0,1.0,0,0,0,0
39,41,0,0.603510,47,0,0.274230,4583.0,21,0.0,12,0,3.0,0,0,0,1
40,42,0,0.715499,40,2,0.642836,3300.0,12,0.0,2,0,0.0,0,0,0,0
41,43,0,0.640014,46,0,0.854994,2592.0,13,0.0,1,0,0.0,0,0,0,0
42,44,0,0.025266,60,0,0.348584,6600.0,8,0.0,2,0,0.0,0,0,0,0
43,45,0,0.190885,67,1,0.274230,1035.0,23,0.0,1,0,0.0,0,0,0,1
44,46,0,0.003449,79,0,0.274230,5450.0,4,0.0,0,0,0.0,1,0,0,1
45,47,0,0.013049,80,0,0.274230,5450.0,2,0.0,0,0,0.0,1,0,1,1
46,48,0,0.222961,56,0,0.457949,10415.0,12,0.0,2,0,3.0,0,0,0,0
47,49,0,0.019542,41,0,0.189562,5000.0,15,0.0,0,0,0.0,0,0,0,0
48,50,0,0.524461,56,0,0.412298,8163.0,9,0.0,2,0,3.0,0,0,0,0
49,51,0,0.083717,52,0,0.105468,9490.0,18,0.0,0,0,0.0,0,0,0,0

In [19]:
bc.dtypes

Unnamed: 0                                int64
SeriousDlqin2yrs                        float64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
dtype: object

In [20]:
bc['SeriousDlqin2yrs']=bc['SeriousDlqin2yrs'].astype(int)

In [21]:
bc.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,101503.000000,101503.0,101503.000000,101503.000000,101503.000000,101503.000000,1.015030e+05,101503.000000,101503.000000,101503.000000,101503.000000,98877.000000
mean,50752.000000,0.0,5.310000,52.405436,0.453770,0.295642,5.497373e+03,8.453514,0.296691,1.013074,0.270317,0.769046
std,29301.536524,0.0,196.156039,14.779756,4.538487,0.198049,3.280790e+04,5.144100,4.515859,1.110253,4.503578,1.136778
min,1.000000,0.0,0.000000,21.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25376.500000,0.0,0.030131,41.000000,0.000000,0.173423,1.600000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,50752.000000,0.0,0.152586,52.000000,0.000000,0.274230,4.367000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,76127.500000,0.0,0.564225,63.000000,0.000000,0.379924,7.374000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,101503.000000,0.0,21821.000000,104.000000,98.000000,1.000000,7.727000e+06,85.000000,98.000000,37.000000,98.000000,43.000000

In [ ]:
# Na coluna 'RevolvingUtilizationOfUnsecuredLines' é notavel valores muito acima do normal podendo ser outliers.
#  Para o tratamento deles irei limitar em 1.0 como o máximo todos valores acima de 1.0 .
#  Exemplo o número 21821 sendo uns dos maiores valores, assim se trasnformando em 1.0 .

In [22]:
limite = 1.0
limite_aceitavel1=bc.loc[bc['RevolvingUtilizationOfUnsecuredLines'] <= limite, 'RevolvingUtilizationOfUnsecuredLines'].median()

In [23]:
limite_aceitavel1

0.14312798049999997

In [24]:
bc.loc[bc['RevolvingUtilizationOfUnsecuredLines'] > limite, 'RevolvingUtilizationOfUnsecuredLines'] = limite_aceitavel1

In [161]:
bc.head(15)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado,Nulos_NumberOfDependents,Limite_DebtRatio
0,1,0,0.885519,43,0,0.177513,5700.0,4,0.0,0,0,0.0,0,0,0,0
1,2,0,0.463295,57,0,0.527237,9141.0,15,0.0,4,0,2.0,0,0,0,0
2,3,0,0.043275,59,0,0.687648,5083.0,12,0.0,1,0,2.0,0,0,0,0
3,4,0,0.280308,38,1,0.925961,3200.0,7,0.0,2,0,0.0,0,0,0,0
4,5,0,1.000000,27,0,0.019917,3865.0,4,0.0,0,0,1.0,0,0,0,0
5,6,0,0.509791,63,0,0.342429,4140.0,4,0.0,0,0,1.0,0,0,0,0
6,7,0,0.587778,50,0,0.274230,5450.0,5,0.0,0,0,3.0,1,0,0,1
7,8,0,0.046149,79,1,0.369170,3301.0,8,0.0,1,0,1.0,0,0,0,0
8,9,0,0.013527,68,0,0.274230,5450.0,4,0.0,1,0,0.0,1,0,0,1
9,11,0,0.028485,37,0,0.319687,7400.0,8,0.0,1,0,1.0,0,0,0,0
10,12,0,0.085077,52,0,0.903552,4250.0,6,0.0,2,0,0.0,0,0,0,0
11,13,0,0.010596,68,0,0.007782,3854.0,16,0.0,0,0,0.0,0,0,0,0
12,14,0,0.380679,30,0,0.377449,2500.0,12,0.0,0,0,1.0,0,0,0,0
13,15,0,0.556894,56,0,0.697347,6822.0,14,0.0,1,0,1.0,0,0,0,0
14,16,0,0.079056,28,0,0.105831,7133.0,8,0.0,0,0,0.0,0,0,0,0

In [28]:
bc.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,101503.000000,101503.0,101503.000000,101503.000000,101503.000000,101503.000000,1.015030e+05,101503.000000,101503.000000,101503.000000,101503.000000,98877.000000
mean,50752.000000,0.0,0.301648,52.405436,0.453770,0.295642,5.497373e+03,8.453514,0.296691,1.013074,0.270317,0.769046
std,29301.536524,0.0,0.336597,14.779756,4.538487,0.198049,3.280790e+04,5.144100,4.515859,1.110253,4.503578,1.136778
min,1.000000,0.0,0.000000,21.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25376.500000,0.0,0.030131,41.000000,0.000000,0.173423,1.600000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,50752.000000,0.0,0.143128,52.000000,0.000000,0.274230,4.367000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,76127.500000,0.0,0.512501,63.000000,0.000000,0.379924,7.374000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,101503.000000,0.0,1.000000,104.000000,98.000000,1.000000,7.727000e+06,85.000000,98.000000,37.000000,98.000000,43.000000

In [33]:
# Outliers em 'NumberOfTime30-59DaysPastDueNotWorse' é notavel que o valor 98 e 96 aparecem frequentemente comparado aos outros, oque poderia ser impossivel,
#por conta que o usuário mesmo tendo 3 ou 4 cartões, chegar em 98 em dois anos não seria possivel, só se o usuário tevesse centenas de cartões e todos
#atrasados em uma quantidade exata.
# SOLUÇÃO= encotrar o 0.1% NumberOfTime30-59DaysPastDueNotWorse' que seria 19 o máximo que uma pessoa pode atrasar e limitar todos resto acima de 20
#para 20
limite_aceitavel2=20
bc.loc[bc['NumberOfTime30-59DaysPastDueNotWorse'] > limite_aceitavel2, 'NumberOfTime30-59DaysPastDueNotWorse'] = 20

In [34]:
#De outra forma
#bc['NumberOfTime30-59DaysPastDueNotWorse']=bc['NumberOfTime30-59DaysPastDueNotWorse'].clip(upper=20)

In [35]:
bc[bc['NumberOfTime30-59DaysPastDueNotWorse'].between(13,98)].sort_values(by='NumberOfTime30-59DaysPastDueNotWorse').head(10)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
58279,58280,0,0.143128,45,19,0.274230,0.0,24,0,2,2,1.0
9,10,0,1.000000,23,20,0.000000,0.0,0,98,0,98,0.0
307,308,0,1.000000,22,20,0.000000,0.0,0,98,0,98,0.0
69,70,0,1.000000,52,20,0.020303,2708.0,0,98,0,98,0.0
1131,1132,0,1.000000,24,20,0.000000,0.0,0,98,0,98,0.0
1166,1167,0,1.000000,21,20,0.000000,0.0,0,98,0,98,NaN
1176,1177,0,1.000000,25,20,0.000000,2935.0,0,98,0,98,0.0
703,704,0,1.000000,23,20,0.000000,0.0,0,98,0,98,NaN
1924,1925,0,1.000000,24,20,0.008384,3100.0,0,98,0,98,1.0
2265,2266,0,1.000000,21,20,0.000000,2088.0,0,98,0,98,0.0

In [42]:
bc.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,101503.000000,101503.0,101503.000000,101503.000000,101503.000000,101503.000000,1.015030e+05,101503.000000,101503.000000,101503.000000,101503.000000,98877.000000
mean,50752.000000,0.0,0.301648,52.405436,0.289341,0.295642,5.497373e+03,8.453514,0.296691,1.013074,0.270317,0.769046
std,29301.536524,0.0,0.336597,14.779756,1.148384,0.198049,3.280790e+04,5.144100,4.515859,1.110253,4.503578,1.136778
min,1.000000,0.0,0.000000,21.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25376.500000,0.0,0.030131,41.000000,0.000000,0.173423,1.600000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,50752.000000,0.0,0.143128,52.000000,0.000000,0.274230,4.367000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,76127.500000,0.0,0.512501,63.000000,0.000000,0.379924,7.374000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,101503.000000,0.0,1.000000,104.000000,20.000000,1.000000,7.727000e+06,85.000000,98.000000,37.000000,98.000000,43.000000

In [ ]:
# Removendo linha 55034 da tabela 'NumberOfOpenCreditLinesAndLoans' com valor de 85 sendo um valor impossivel para um usuário ter créditos e emprestimos ativos as mesmo tempo, mesmo sendo uma pessoa
#muito rica não seria possivel, e permanecendo com o restdo dos valores.
# Usando tambem um limitar em 65 como o valor mais próximo e válido dentro da tabela 'NumberOfOpenCreditLinesAndLoans'.

In [41]:
bc.loc[bc['NumberOfOpenCreditLinesAndLoans'] > 0, 'NumberOfOpenCreditLinesAndLoans'].median()

8.0

In [47]:
linha_outlier = bc[bc['NumberOfOpenCreditLinesAndLoans'] == 85].index

In [48]:
linha_outlier

Index([55034], dtype='int64')

In [49]:
bc=bc.drop(linha_outlier)

In [50]:
bc.loc[bc['NumberOfOpenCreditLinesAndLoans'] == 85]

Empty DataFrame
Columns: [Unnamed: 0, SeriousDlqin2yrs, RevolvingUtilizationOfUnsecuredLines, age, NumberOfTime30-59DaysPastDueNotWorse, DebtRatio, MonthlyIncome, NumberOfOpenCreditLinesAndLoans, NumberOfTimes90DaysLate, NumberRealEstateLoansOrLines, NumberOfTime60-89DaysPastDueNotWorse, NumberOfDependents]
Index: []

In [53]:
bc.loc[bc['NumberOfOpenCreditLinesAndLoans']>= 65].sort_values(by='NumberOfOpenCreditLinesAndLoans').head(55)

Empty DataFrame
Columns: [Unnamed: 0, SeriousDlqin2yrs, RevolvingUtilizationOfUnsecuredLines, age, NumberOfTime30-59DaysPastDueNotWorse, DebtRatio, MonthlyIncome, NumberOfOpenCreditLinesAndLoans, NumberOfTimes90DaysLate, NumberRealEstateLoansOrLines, NumberOfTime60-89DaysPastDueNotWorse, NumberOfDependents]
Index: []

In [54]:
limite_NumberOfOpenCreditLinesAndLoans= 65

In [55]:
bc.loc[bc['NumberOfOpenCreditLinesAndLoans'] > limite_NumberOfOpenCreditLinesAndLoans, 'NumberOfOpenCreditLinesAndLoans'] =65

In [168]:
bc.head(15)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado,Nulos_NumberOfDependents,Limite_DebtRatio
0,1,0,0.885519,43,0,0.177513,5700.0,4,0.0,0,0,0.0,0,0,0,0
1,2,0,0.463295,57,0,0.527237,9141.0,15,0.0,4,0,2.0,0,0,0,0
2,3,0,0.043275,59,0,0.687648,5083.0,12,0.0,1,0,2.0,0,0,0,0
3,4,0,0.280308,38,1,0.925961,3200.0,7,0.0,2,0,0.0,0,0,0,0
4,5,0,1.000000,27,0,0.019917,3865.0,4,0.0,0,0,1.0,0,0,0,0
5,6,0,0.509791,63,0,0.342429,4140.0,4,0.0,0,0,1.0,0,0,0,0
6,7,0,0.587778,50,0,0.274230,5450.0,5,0.0,0,0,3.0,1,0,0,1
7,8,0,0.046149,79,1,0.369170,3301.0,8,0.0,1,0,1.0,0,0,0,0
8,9,0,0.013527,68,0,0.274230,5450.0,4,0.0,1,0,0.0,1,0,0,1
9,11,0,0.028485,37,0,0.319687,7400.0,8,0.0,1,0,1.0,0,0,0,0
10,12,0,0.085077,52,0,0.903552,4250.0,6,0.0,2,0,0.0,0,0,0,0
11,13,0,0.010596,68,0,0.007782,3854.0,16,0.0,0,0,0.0,0,0,0,0
12,14,0,0.380679,30,0,0.377449,2500.0,12,0.0,0,0,1.0,0,0,0,0
13,15,0,0.556894,56,0,0.697347,6822.0,14,0.0,1,0,1.0,0,0,0,0
14,16,0,0.079056,28,0,0.105831,7133.0,8,0.0,0,0,0.0,0,0,0,0

In [57]:
# Visualizando tabela 'MonthlyIncome',Converter os valores 0 para NaN(Apenas se souber se a renda é realmente é 0), Então criar uma nova tabela de 0 e 1
#com o nome 'MonthlyIncome_Modificada' para que todas as linhas em NaN em 'MonthlyIncome' sejam informadas na nova tabela como 0 (informando renda) e 
#1 não informando renda.

In [58]:
bc['MonthlyIncome']=bc['MonthlyIncome'].replace(0,np.nan)

In [59]:
bc['MonthlyIncome_Modificada']=bc['MonthlyIncome'].isna().astype(int)

In [60]:
media_renda1=bc['MonthlyIncome'].median()

In [61]:
bc['MonthlyIncome']=bc['MonthlyIncome'].fillna(media_renda1)

In [62]:
bc.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada
count,101502.000000,101502.0,101502.000000,101502.000000,101502.000000,101502.000000,1.015020e+05,101502.000000,101502.000000,101502.000000,101502.00000,98876.000000,101502.000000
mean,50751.957804,0.0,0.301650,52.405490,0.289344,0.295642,6.631542e+03,8.452760,0.296694,1.013074,0.27032,0.769054,0.208094
std,29301.677781,0.0,0.336598,14.779819,1.148389,0.198050,3.269241e+04,5.138512,4.515881,1.110259,4.50360,1.136781,0.405947
min,1.000000,0.0,0.000000,21.000000,0.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,25376.250000,0.0,0.030131,41.000000,0.000000,0.173423,4.000000e+03,5.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,50751.500000,0.0,0.143128,52.000000,0.000000,0.274230,5.450000e+03,8.000000,0.000000,1.000000,0.00000,0.000000,0.000000
75%,76127.750000,0.0,0.512504,63.000000,0.000000,0.379924,7.374000e+03,11.000000,0.000000,2.000000,0.00000,1.000000,0.000000
max,101503.000000,0.0,1.000000,104.000000,20.000000,1.000000,7.727000e+06,63.000000,98.000000,37.000000,98.00000,43.000000,1.000000

In [63]:
bc.loc[bc['NumberOfTimes90DaysLate'] >=50].sort_values(by='NumberOfTimes90DaysLate').head(50)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada
14534,14535,0,1.0,55,20,0.000000,5450.0,1,96,0,96,1.0,1
9,10,0,1.0,23,20,0.000000,5450.0,0,98,0,98,0.0,1
307,308,0,1.0,22,20,0.000000,5450.0,0,98,0,98,0.0,1
69,70,0,1.0,52,20,0.020303,2708.0,0,98,0,98,0.0,0
1131,1132,0,1.0,24,20,0.000000,5450.0,0,98,0,98,0.0,1
1166,1167,0,1.0,21,20,0.000000,5450.0,0,98,0,98,NaN,1
1176,1177,0,1.0,25,20,0.000000,2935.0,0,98,0,98,0.0,0
703,704,0,1.0,23,20,0.000000,5450.0,0,98,0,98,NaN,1
1924,1925,0,1.0,24,20,0.008384,3100.0,0,98,0,98,1.0,0
2265,2266,0,1.0,21,20,0.000000,2088.0,0,98,0,98,0.0,0
2667,2668,0,1.0,40,20,0.000000,5450.0,0,98,0,98,NaN,1
3088,3089,0,1.0,21,20,0.000000,5450.0,0,98,0,98,0.0,1
3150,3151,0,1.0,47,20,0.000000,2400.0,0,98,0,98,0.0,0
3202,3203,0,1.0,25,20,0.015570,1990.0,0,98,0,98,0.0,0
4073,4074,0,1.0,23,20,0.000000,5450.0,0,98,0,98,0.0,1
1646,1647,0,1.0,22,20,0.000000,2100.0,0,98,0,98,0.0,0
5012,5013,0,1.0,21,20,0.000000,5450.0,0,98,0,98,0.0,1
5108,5109,0,1.0,24,20,0.000000,5450.0,0,98,0,98,0.0,1
5955,5956,0,1.0,21,20,0.000000,5450.0,0,98,0,98,0.0,1
9053,9054,0,1.0,23,20,0.000000,5450.0,0,98,0,98,0.0,1
9742,9743,0,1.0,38,20,0.000000,5450.0,0,98,0,98,0.0,1
9970,9971,0,1.0,22,20,0.000000,5450.0,0,98,0,98,0.0,1
10292,10293,0,1.0,26,20,0.000000,5450.0,0,98,0,98,0.0,1
10536,10537,0,1.0,31,20,0.000000,2576.0,0,98,0,98,1.0,0
10721,10722,0,1.0,22,20,0.000000,5450.0,0,98,0,98,0.0,1
10874,10875,0,1.0,44,20,0.000000,5450.0,0,98,0,98,0.0,1
11252,11253,0,1.0,68,20,0.274230,5450.0,0,98,0,98,0.0,1
11455,11456,0,1.0,57,20,0.000000,3000.0,0,98,0,98,0.0,0
12074,12075,0,1.0,23,20,0.065773,820.0,0,98,0,98,0.0,0
12770,12771,0,1.0,48,20,0.000000,5450.0,0,98,0,98,3.0,1
13458,13459,0,1.0,51,20,0.000000,5450.0,0,98,0,98,0.0,1
4443,4444,0,1.0,25,20,0.000000,5450.0,0,98,0,98,0.0,1
14116,14117,0,1.0,55,20,0.000000,2080.0,0,98,0,98,0.0,0
14365,14366,0,1.0,64,20,0.274230,5450.0,0,98,0,98,0.0,1
14591,14592,0,1.0,39,20,0.000000,5300.0,0,98,0,98,3.0,0
14622,14623,0,1.0,65,20,0.000000,5450.0,0,98,0,98,0.0,1
15690,15691,0,1.0,43,20,0.001428,2100.0,0,98,0,98,3.0,0
15867,15868,0,1.0,21,20,0.000000,5450.0,0,98,0,98,NaN,1
15956,15957,0,1.0,24,20,0.000000,5450.0,0,98,0,98,0.0,1
15973,15974,0,1.0,39,20,0.000000,3100.0,0,98,0,98,3.0,0
16176,16177,0,1.0,29,20,0.000000,1200.0,0,98,0,98,2.0,0
16472,16473,0,1.0,40,20,0.274230,5450.0,0,98,0,98,0.0,1
16647,16648,0,1.0,31,20,0.006397,2500.0,0,98,0,98,0.0,0
17121,17122,0,1.0,25,20,0.000000,5450.0,0,98,0,98,0.0,1
18933,18934,0,1.0,56,20,0.000000,5450.0,0,98,0,98,0.0,1
19100,19101,0,1.0,37,20,0.274230,5450.0,0,98,0,98,0.0,1
19266,19267,0,1.0,28,20,0.058002,930.0,0,98,0,98,0.0,0
19676,19677,0,1.0,24,20,0.000000,5450.0,0,98,0,98,0.0,1
20285,20286,0,1.0,30,20,0.000000,5450.0,0,98,0,98,NaN,1
20782,20783,0,1.0,27,20,0.274230,5450.0,0,98,0,98,0.0,1

In [64]:
#  Em 'NumberOfTimes90DaysLate' notamos que existe valores com uma variação muito alta, Criaremos uma nova tabela chamada 'Sentinela90_atrasado',
#com finalidade em pegar os valores 96 e 98 onde ocorre a maior variação desde o 18, sendo assim 96 e 98 sendo 1 e o resto 0.
#  Na tabela principal 'NumberOfTimes90DaysLate' os valores que tem como 96 e 98 deixar em NaN, para não interferir no calculo da médiana, logo assim sabendo
#a médiana, inserimos nos valores 96 e 98 que seria 0.

In [65]:
bc['NumberOfTimes90DaysLate'].value_counts().sort_index(ascending=False)

NumberOfTimes90DaysLate
98      213
96        1
18        1
17        1
16        1
12        1
11        1
10        2
9        14
8        19
7        26
6        44
5       102
4       191
3       445
2      1062
1      3594
0     95784
Name: count, dtype: int64

In [66]:
bc['Sentinela90_atrasado']=bc['NumberOfTimes90DaysLate'].isin([96,98]).astype(int)

In [67]:
bc['NumberOfTimes90DaysLate']=bc['NumberOfTimes90DaysLate'].replace([96,98], np.nan)

In [68]:
bc['NumberOfTimes90DaysLate'].median()

0.0

In [69]:
bc['NumberOfTimes90DaysLate']=bc['NumberOfTimes90DaysLate'].fillna(bc['NumberOfTimes90DaysLate'].median())

In [70]:
bc.head(55)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado
0,1,0,0.885519,43,0,0.177513,5700.0,4,0.0,0,0,0.0,0,0
1,2,0,0.463295,57,0,0.527237,9141.0,15,0.0,4,0,2.0,0,0
2,3,0,0.043275,59,0,0.687648,5083.0,12,0.0,1,0,2.0,0,0
3,4,0,0.280308,38,1,0.925961,3200.0,7,0.0,2,0,0.0,0,0
4,5,0,1.000000,27,0,0.019917,3865.0,4,0.0,0,0,1.0,0,0
5,6,0,0.509791,63,0,0.342429,4140.0,4,0.0,0,0,1.0,0,0
6,7,0,0.587778,50,0,0.274230,5450.0,5,0.0,0,0,3.0,1,0
7,8,0,0.046149,79,1,0.369170,3301.0,8,0.0,1,0,1.0,0,0
8,9,0,0.013527,68,0,0.274230,5450.0,4,0.0,1,0,0.0,1,0
9,10,0,1.000000,23,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
10,11,0,0.028485,37,0,0.319687,7400.0,8,0.0,1,0,1.0,0,0
11,12,0,0.085077,52,0,0.903552,4250.0,6,0.0,2,0,0.0,0,0
12,13,0,0.010596,68,0,0.007782,3854.0,16,0.0,0,0,0.0,0,0
13,14,0,0.380679,30,0,0.377449,2500.0,12,0.0,0,0,1.0,0,0
14,15,0,0.556894,56,0,0.697347,6822.0,14,0.0,1,0,1.0,0,0
15,16,0,0.079056,28,0,0.105831,7133.0,8,0.0,0,0,0.0,0,0
16,17,0,0.543013,72,0,0.461786,5900.0,10,0.0,2,0,1.0,0,0
17,18,0,0.112346,37,0,0.144326,2916.0,7,0.0,0,0,0.0,0,0
18,19,0,0.648285,29,0,0.174850,4500.0,4,0.0,0,1,1.0,0,0
19,20,0,0.686406,43,0,0.274230,5450.0,10,0.0,0,0,1.0,1,0
20,21,0,0.085910,48,0,0.196156,8844.0,8,0.0,1,0,1.0,0,0
21,22,0,0.158549,61,0,0.353158,11920.0,13,0.0,1,0,0.0,0,0
22,23,0,0.009303,69,0,0.384451,6083.0,4,0.0,2,0,0.0,0,0
23,24,0,0.957442,69,2,0.666338,3041.0,8,1.0,1,1,1.0,0,0
24,25,0,0.442489,50,1,0.286555,8500.0,17,0.0,1,0,2.0,0,0
25,26,0,0.125267,51,0,0.274230,5450.0,10,0.0,2,0,0.0,1,0
26,27,0,1.000000,45,0,0.000000,4750.0,1,0.0,0,0,1.0,0,0
27,28,0,0.181481,67,0,0.274230,5450.0,12,0.0,1,0,0.0,1,0
28,29,0,0.729397,34,0,0.335555,7500.0,6,0.0,2,0,1.0,0,0
29,30,0,0.024445,47,0,0.274230,5450.0,20,0.0,2,0,2.0,1,0
30,31,0,0.691411,44,0,0.173777,4804.0,10,0.0,0,0,0.0,0,0
31,32,0,0.000000,55,0,0.274230,5450.0,5,0.0,1,0,0.0,1,0
32,33,0,0.000000,57,0,0.212447,4000.0,12,0.0,0,0,0.0,0,0
33,34,0,0.817480,54,0,0.132721,4354.0,6,0.0,0,0,0.0,0,0
34,35,0,0.143128,61,4,0.261173,8166.0,14,0.0,1,0,1.0,0,0
35,36,0,0.423358,49,0,0.616301,2600.0,13,0.0,1,0,1.0,0,0
36,37,0,0.282515,32,0,0.492901,5000.0,10,0.0,1,0,1.0,0,0
37,38,0,0.142127,56,0,0.274230,5450.0,9,0.0,2,0,2.0,1,0
38,39,0,0.022738,41,0,0.343161,5833.0,5,0.0,1,0,3.0,0,0
39,40,0,0.005893,57,1,0.386379,11819.0,25,0.0,4,0,1.0,0,0
40,41,0,0.603510,47,0,0.274230,4583.0,21,0.0,12,0,3.0,0,0
41,42,0,0.715499,40,2,0.642836,3300.0,12,0.0,2,0,0.0,0,0
42,43,0,0.640014,46,0,0.854994,2592.0,13,0.0,1,0,0.0,0,0
43,44,0,0.025266,60,0,0.348584,6600.0,8,0.0,2,0,0.0,0,0
44,45,0,0.190885,67,1,0.274230,1035.0,23,0.0,1,0,0.0,0,0
45,46,0,0.003449,79,0,0.274230,5450.0,4,0.0,0,0,0.0,1,0
46,47,0,0.013049,80,0,0.274230,5450.0,2,0.0,0,0,NaN,1,0
47,48,0,0.222961,56,0,0.457949,10415.0,12,0.0,2,0,3.0,0,0
48,49,0,0.019542,41,0,0.189562,5000.0,15,0.0,0,0,0.0,0,0
49,50,0,0.524461,56,0,0.412298,8163.0,9,0.0,2,0,3.0,0,0
50,51,0,0.083717,52,0,0.105468,9490.0,18,0.0,0,0,0.0,0,0
51,52,0,0.127141,87,0,0.135946,2500.0,14,0.0,0,0,0.0,0,0
52,53,0,0.004229,45,0,0.282129,8605.0,5,0.0,2,0,1.0,0,0
53,54,0,1.000000,48,0,0.299959,4883.0,4,0.0,2,0,0.0,0,0
54,55,0,0.098284,36,0,0.375485,5416.0,13,0.0,1,0,0.0,0,0

In [71]:
bc.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado
count,101502.000000,101502.0,101502.000000,101502.000000,101502.000000,101502.000000,1.015020e+05,101502.000000,101502.000000,101502.000000,101502.00000,98876.000000,101502.000000,101502.000000
mean,50751.957804,0.0,0.301650,52.405490,0.289344,0.295642,6.631542e+03,8.452760,0.090097,1.013074,0.27032,0.769054,0.208094,0.002108
std,29301.677781,0.0,0.336598,14.779819,1.148389,0.198050,3.269241e+04,5.138512,0.477791,1.110259,4.50360,1.136781,0.405947,0.045868
min,1.000000,0.0,0.000000,21.000000,0.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,25376.250000,0.0,0.030131,41.000000,0.000000,0.173423,4.000000e+03,5.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
50%,50751.500000,0.0,0.143128,52.000000,0.000000,0.274230,5.450000e+03,8.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000
75%,76127.750000,0.0,0.512504,63.000000,0.000000,0.379924,7.374000e+03,11.000000,0.000000,2.000000,0.00000,1.000000,0.000000,0.000000
max,101503.000000,0.0,1.000000,104.000000,20.000000,1.000000,7.727000e+06,63.000000,18.000000,37.000000,98.00000,43.000000,1.000000,1.000000

In [72]:
#  Em 'NumberRealEstateLoansOrLines' parece estar tudo correto, sem correspondência de outliers e sem número nulos, os números altos correspodem a altas
# rendas mensais e sem 'MonthlyIncome_Modificada'(Rendas nulas).

In [73]:
bc['NumberRealEstateLoansOrLines'].value_counts().sort_index(ascending=False)

NumberRealEstateLoansOrLines
37        1
29        1
25        1
21        1
20        1
19        2
18        1
16        2
15        4
14        9
13        5
12       11
11       19
10       23
9        49
8        58
7       108
6       227
5       452
4      1414
3      4423
2     20955
1     35669
0     38066
Name: count, dtype: int64

In [74]:
print(bc['NumberRealEstateLoansOrLines'].describe())

count    101502.000000
mean          1.013074
std           1.110259
min           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
max          37.000000
Name: NumberRealEstateLoansOrLines, dtype: float64

In [75]:
bc['NumberRealEstateLoansOrLines'].isnull().sum()

np.int64(0)

In [76]:
bc.loc[bc['NumberRealEstateLoansOrLines'] >=15]

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado
95,96,0,0.005575,68,1,0.274230,15670.0,32,0.0,21,0,0.0,0,0
6570,6571,0,0.195694,55,0,0.585165,20612.0,36,0.0,15,0,0.0,0,0
8977,8978,0,0.079942,56,0,0.274230,19832.0,21,0.0,18,0,0.0,0,0
16895,16896,0,0.581460,67,0,0.756545,61000.0,44,0.0,25,0,0.0,0,0
24905,24906,0,0.466175,60,0,0.274230,13080.0,43,0.0,16,0,2.0,0,0
30615,30616,0,0.225813,50,0,0.584590,40766.0,24,0.0,19,0,0.0,0,0
45850,45851,0,0.252866,62,0,0.441075,41416.0,24,0.0,15,0,2.0,0,0
61575,61576,0,0.224621,57,0,0.274230,14250.0,32,0.0,20,0,0.0,0,0
63263,63264,0,0.011351,45,0,0.274230,6274.0,24,0.0,16,0,2.0,0,0
75452,75453,0,0.197780,61,0,0.274230,20000.0,34,0.0,29,0,0.0,0,0
87260,87261,0,0.481516,46,0,0.834348,17083.0,26,0.0,19,0,2.0,0,0
87339,87340,0,0.279738,38,0,0.807579,25833.0,24,0.0,15,0,1.0,0,0
90721,90722,0,0.123796,70,0,0.631427,39500.0,45,0.0,37,0,1.0,0,0
94318,94319,0,0.495201,47,1,0.824522,8000.0,26,0.0,15,0,5.0,0,0

In [77]:
#  Em 'NumberOfTime60-89DaysPastDueNotWorse' é possivel identicar alguns outliers que são correspondentes a 'RevolvingUtilizationOfUnsecuredLines',
#'NumberOfTime30-59DaysPastDueNotWorse' e 'Sentinela90_atrasado' onde todos correspondem a mesma coisa, sendo assim coerente remover todas as linhas 
#entre 96 e 98 de 'NumberOfTime60-89DaysPastDueNotWorse' correspondente a outras tabelas.

In [78]:
bc['NumberOfTime60-89DaysPastDueNotWorse'].value_counts().sort_index(ascending=False)

NumberOfTime60-89DaysPastDueNotWorse
98      213
96        1
9         3
8         1
7         7
6         7
5        25
4        61
3       216
2       731
1      3863
0     96374
Name: count, dtype: int64

In [79]:
bc['NumberOfTime60-89DaysPastDueNotWorse'].describe()

count    101502.00000
mean          0.27032
std           4.50360
min           0.00000
25%           0.00000
50%           0.00000
75%           0.00000
max          98.00000
Name: NumberOfTime60-89DaysPastDueNotWorse, dtype: float64

In [80]:
bc['NumberOfTime60-89DaysPastDueNotWorse'].isnull().sum()

np.int64(0)

In [81]:
bc.loc[bc['NumberOfTime60-89DaysPastDueNotWorse'] >= 96].sort_values(by='NumberOfTime60-89DaysPastDueNotWorse',ascending=True).head(40)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado
14534,14535,0,1.0,55,20,0.000000,5450.0,1,0.0,0,96,1.0,1,1
9,10,0,1.0,23,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
307,308,0,1.0,22,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
69,70,0,1.0,52,20,0.020303,2708.0,0,0.0,0,98,0.0,0,1
1131,1132,0,1.0,24,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
1166,1167,0,1.0,21,20,0.000000,5450.0,0,0.0,0,98,NaN,1,1
1176,1177,0,1.0,25,20,0.000000,2935.0,0,0.0,0,98,0.0,0,1
703,704,0,1.0,23,20,0.000000,5450.0,0,0.0,0,98,NaN,1,1
1924,1925,0,1.0,24,20,0.008384,3100.0,0,0.0,0,98,1.0,0,1
2265,2266,0,1.0,21,20,0.000000,2088.0,0,0.0,0,98,0.0,0,1
2667,2668,0,1.0,40,20,0.000000,5450.0,0,0.0,0,98,NaN,1,1
3088,3089,0,1.0,21,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
3150,3151,0,1.0,47,20,0.000000,2400.0,0,0.0,0,98,0.0,0,1
3202,3203,0,1.0,25,20,0.015570,1990.0,0,0.0,0,98,0.0,0,1
4073,4074,0,1.0,23,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
1646,1647,0,1.0,22,20,0.000000,2100.0,0,0.0,0,98,0.0,0,1
5012,5013,0,1.0,21,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
5108,5109,0,1.0,24,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
5955,5956,0,1.0,21,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
9053,9054,0,1.0,23,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
9742,9743,0,1.0,38,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
9970,9971,0,1.0,22,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
10292,10293,0,1.0,26,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
10536,10537,0,1.0,31,20,0.000000,2576.0,0,0.0,0,98,1.0,0,1
10721,10722,0,1.0,22,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
10874,10875,0,1.0,44,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
11252,11253,0,1.0,68,20,0.274230,5450.0,0,0.0,0,98,0.0,1,1
11455,11456,0,1.0,57,20,0.000000,3000.0,0,0.0,0,98,0.0,0,1
12074,12075,0,1.0,23,20,0.065773,820.0,0,0.0,0,98,0.0,0,1
12770,12771,0,1.0,48,20,0.000000,5450.0,0,0.0,0,98,3.0,1,1
13458,13459,0,1.0,51,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
4443,4444,0,1.0,25,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
14116,14117,0,1.0,55,20,0.000000,2080.0,0,0.0,0,98,0.0,0,1
14365,14366,0,1.0,64,20,0.274230,5450.0,0,0.0,0,98,0.0,1,1
14591,14592,0,1.0,39,20,0.000000,5300.0,0,0.0,0,98,3.0,0,1
14622,14623,0,1.0,65,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
15690,15691,0,1.0,43,20,0.001428,2100.0,0,0.0,0,98,3.0,0,1
15867,15868,0,1.0,21,20,0.000000,5450.0,0,0.0,0,98,NaN,1,1
15956,15957,0,1.0,24,20,0.000000,5450.0,0,0.0,0,98,0.0,1,1
15973,15974,0,1.0,39,20,0.000000,3100.0,0,0.0,0,98,3.0,0,1

In [82]:
mask = bc['NumberOfTime60-89DaysPastDueNotWorse'] >=96

In [83]:
bc[mask]['NumberOfTime30-59DaysPastDueNotWorse'].value_counts()

NumberOfTime30-59DaysPastDueNotWorse
20    214
Name: count, dtype: int64

In [84]:
bc[mask]['RevolvingUtilizationOfUnsecuredLines'].value_counts()

RevolvingUtilizationOfUnsecuredLines
1.0    214
Name: count, dtype: int64

In [85]:
bc[mask]['NumberOfOpenCreditLinesAndLoans'].value_counts()

NumberOfOpenCreditLinesAndLoans
0    213
1      1
Name: count, dtype: int64

In [86]:
corrompidos = bc['NumberOfTime60-89DaysPastDueNotWorse'].isin([96, 98])

In [87]:
 bc=bc[~corrompidos].reset_index(drop=True)

In [88]:
bc.loc[bc['NumberOfTime60-89DaysPastDueNotWorse'] >=96]

Empty DataFrame
Columns: [Unnamed: 0, SeriousDlqin2yrs, RevolvingUtilizationOfUnsecuredLines, age, NumberOfTime30-59DaysPastDueNotWorse, DebtRatio, MonthlyIncome, NumberOfOpenCreditLinesAndLoans, NumberOfTimes90DaysLate, NumberRealEstateLoansOrLines, NumberOfTime60-89DaysPastDueNotWorse, NumberOfDependents, MonthlyIncome_Modificada, Sentinela90_atrasado]
Index: []

In [89]:
bc.head(30)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado
0,1,0,0.885519,43,0,0.177513,5700.0,4,0.0,0,0,0.0,0,0
1,2,0,0.463295,57,0,0.527237,9141.0,15,0.0,4,0,2.0,0,0
2,3,0,0.043275,59,0,0.687648,5083.0,12,0.0,1,0,2.0,0,0
3,4,0,0.280308,38,1,0.925961,3200.0,7,0.0,2,0,0.0,0,0
4,5,0,1.000000,27,0,0.019917,3865.0,4,0.0,0,0,1.0,0,0
5,6,0,0.509791,63,0,0.342429,4140.0,4,0.0,0,0,1.0,0,0
6,7,0,0.587778,50,0,0.274230,5450.0,5,0.0,0,0,3.0,1,0
7,8,0,0.046149,79,1,0.369170,3301.0,8,0.0,1,0,1.0,0,0
8,9,0,0.013527,68,0,0.274230,5450.0,4,0.0,1,0,0.0,1,0
9,11,0,0.028485,37,0,0.319687,7400.0,8,0.0,1,0,1.0,0,0
10,12,0,0.085077,52,0,0.903552,4250.0,6,0.0,2,0,0.0,0,0
11,13,0,0.010596,68,0,0.007782,3854.0,16,0.0,0,0,0.0,0,0
12,14,0,0.380679,30,0,0.377449,2500.0,12,0.0,0,0,1.0,0,0
13,15,0,0.556894,56,0,0.697347,6822.0,14,0.0,1,0,1.0,0,0
14,16,0,0.079056,28,0,0.105831,7133.0,8,0.0,0,0,0.0,0,0
15,17,0,0.543013,72,0,0.461786,5900.0,10,0.0,2,0,1.0,0,0
16,18,0,0.112346,37,0,0.144326,2916.0,7,0.0,0,0,0.0,0,0
17,19,0,0.648285,29,0,0.174850,4500.0,4,0.0,0,1,1.0,0,0
18,20,0,0.686406,43,0,0.274230,5450.0,10,0.0,0,0,1.0,1,0
19,21,0,0.085910,48,0,0.196156,8844.0,8,0.0,1,0,1.0,0,0
20,22,0,0.158549,61,0,0.353158,11920.0,13,0.0,1,0,0.0,0,0
21,23,0,0.009303,69,0,0.384451,6083.0,4,0.0,2,0,0.0,0,0
22,24,0,0.957442,69,2,0.666338,3041.0,8,1.0,1,1,1.0,0,0
23,25,0,0.442489,50,1,0.286555,8500.0,17,0.0,1,0,2.0,0,0
24,26,0,0.125267,51,0,0.274230,5450.0,10,0.0,2,0,0.0,1,0
25,27,0,1.000000,45,0,0.000000,4750.0,1,0.0,0,0,1.0,0,0
26,28,0,0.181481,67,0,0.274230,5450.0,12,0.0,1,0,0.0,1,0
27,29,0,0.729397,34,0,0.335555,7500.0,6,0.0,2,0,1.0,0,0
28,30,0,0.024445,47,0,0.274230,5450.0,20,0.0,2,0,2.0,1,0
29,31,0,0.691411,44,0,0.173777,4804.0,10,0.0,0,0,0.0,0,0

In [90]:
bc.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado
count,101288.000000,101288.0,101288.000000,101288.000000,101288.000000,101288.000000,1.012880e+05,101288.000000,101288.000000,101288.000000,101288.000000,98685.000000,101288.000000,101288.0
mean,50757.480225,0.0,0.300175,52.445443,0.247700,0.296215,6.637235e+03,8.470609,0.090287,1.015214,0.063858,0.769712,0.207478,0.0
std,29302.650323,0.0,0.335417,14.757765,0.706401,0.197837,3.272657e+04,5.129227,0.478277,1.110453,0.326856,1.137111,0.405503,0.0
min,1.000000,0.0,0.000000,21.000000,0.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,25380.750000,0.0,0.029994,41.000000,0.000000,0.174496,4.000000e+03,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
50%,50757.500000,0.0,0.143128,52.000000,0.000000,0.274230,5.450000e+03,8.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0
75%,76137.250000,0.0,0.509003,63.000000,0.000000,0.380405,7.385250e+03,11.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.0
max,101503.000000,0.0,1.000000,104.000000,19.000000,1.000000,7.727000e+06,63.000000,18.000000,37.000000,9.000000,43.000000,1.000000,0.0

In [ ]:
#  Verificando a tabela 'NumberOfDependents' é notavel os valores 43 e 20 muito altos e isolados dos normais e tambem presença de valores Nulos.
# Com isso, é necessário a criação de uma outra tabela('Nulos_NumberOfDependents') dos valores Nulos com 1 e 0 sendo 1 na presença de valores Nulos.
# Logo em seguida calcular a mediana da tabela 'NumberOfDependents' e colocar na tabela principal, sendo a mediana como 1 na tabela 'Nulos_NumberOfDependents'.
# E também limitar em 10 o valor máximo da tabela 'NumberOfDependents'.

In [92]:
bc['NumberOfDependents'].value_counts().sort_index(ascending=False)

NumberOfDependents
43.0        1
20.0        1
10.0        3
9.0         3
8.0        16
7.0        50
6.0       125
5.0       526
4.0      1992
3.0      6617
2.0     13282
1.0     17598
0.0     58471
Name: count, dtype: int64

In [101]:
bc['NumberOfDependents'].isnull().sum()

np.int64(2603)

In [99]:
bc.loc[bc['NumberOfDependents'] == 2].sort_values(by = 'NumberOfDependents',ascending=True).head(15)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado
101275,101491,0,0.875649,43,2,0.512893,9500.0,8,0.0,5,0,2.0,0,0
101267,101482,0,0.048971,51,0,0.339154,7043.0,14,0.0,1,0,2.0,0,0
101264,101479,0,0.000000,43,0,0.095303,5833.0,6,0.0,1,0,2.0,0,0
101261,101476,0,1.000000,35,0,0.240467,1284.0,1,0.0,0,0,2.0,0,0
101248,101463,0,0.029086,47,0,0.299370,10000.0,8,0.0,2,0,2.0,0,0
101238,101453,0,0.055424,53,0,0.184494,8525.0,5,0.0,1,0,2.0,0,0
101237,101452,0,0.000000,49,3,0.302577,13850.0,7,0.0,3,1,2.0,0,0
101227,101442,0,0.240630,59,0,0.646640,24000.0,12,0.0,6,0,2.0,0,0
101224,101439,0,0.059631,37,0,0.123313,6000.0,7,0.0,0,0,2.0,0,0
101211,101426,0,0.176939,46,0,0.441516,3376.0,5,0.0,2,0,2.0,0,0
101209,101424,0,0.798160,38,0,0.526438,5162.0,8,3.0,2,1,2.0,0,0
101206,101421,0,0.000000,58,0,0.668267,10833.0,13,0.0,4,0,2.0,0,0
101187,101402,0,0.670438,46,0,0.580584,11000.0,10,0.0,2,0,2.0,0,0
101186,101401,0,0.031392,49,0,0.004999,6000.0,2,0.0,0,0,2.0,0,0
101180,101395,0,0.097474,47,0,0.467242,7066.0,9,0.0,2,0,2.0,0,0

In [104]:
bc['Nulos_NumberOfDependents']=bc['NumberOfDependents'].isna().astype(int)

In [106]:
bc.loc[bc['Nulos_NumberOfDependents'] ==1]

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_Modificada,Sentinela90_atrasado,Nulos_NumberOfDependents
45,47,0,0.013049,80,0,0.27423,5450.0,2,0.0,0,0,NaN,1,0,1
78,81,0,0.085647,47,0,0.27423,5450.0,9,0.0,0,0,NaN,1,0,1
196,199,0,0.024887,51,0,0.27423,5450.0,10,0.0,1,0,NaN,1,0,1
236,239,0,0.000000,27,0,0.00000,5450.0,2,0.0,0,0,NaN,1,0,1
248,251,0,1.000000,66,0,0.00000,5450.0,2,0.0,0,0,NaN,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100932,101146,0,0.000000,27,0,0.00000,5450.0,1,0.0,0,0,NaN,1,0,1
101174,101389,0,0.012208,70,0,0.27423,5450.0,9,0.0,0,0,NaN,1,0,1
101217,101432,0,0.076296,77,0,0.27423,5450.0,1,0.0,0,0,NaN,1,0,1
101246,101461,0,1.000000,24,0,0.27423,5450.0,0,1.0,0,0,NaN,1,0,1
101285,101501,0,0.081596,70,0,0.27423,5450.0,3,0.0,0,0,NaN,1,0,1

In [108]:
bc['NumberOfDependents'].median()

0.0

In [110]:
bc['NumberOfDependents'].fillna(bc['NumberOfDependents'].median(),inplace=True)

In [112]:
bc.loc[bc['NumberOfDependents'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, SeriousDlqin2yrs, RevolvingUtilizationOfUnsecuredLines, age, NumberOfTime30-59DaysPastDueNotWorse, DebtRatio, MonthlyIncome, NumberOfOpenCreditLinesAndLoans, NumberOfTimes90DaysLate, NumberRealEstateLoansOrLines, NumberOfTime60-89DaysPastDueNotWorse, NumberOfDependents, MonthlyIncome_Modificada, Sentinela90_atrasado, Nulos_NumberOfDependents]
Index: []

In [ ]:
bc['NumberOfDependents']=bc['NumberOfDependents'].clip(upper=10)

In [ ]:
--------------------------------------------------------------------------------------------------------------------------------------------------------